import type { Express } from "express";
import { authRouter } from "../routes/auth.routes.js";
import { worldRouter } from "../routes/world.routes.js";
import { companyRouter } from "../routes/company.routes.js";
import { agentRouter } from "../routes/agent.routes.js";
import { taskRouter } from "../routes/task.routes.js";
import { conversationRouter } from "../routes/conversation.routes.js";
import { memoryRouter } from "../routes/memory.routes.js";
import { economyRouter } from "../routes/economy.routes.js";
import { approvalRouter } from "../routes/approval.routes.js";
import { toolRouter } from "../routes/tool.routes.js";
import { eventRouter } from "../routes/event.routes.js";
import { simulationRouter } from "../routes/simulation.routes.js";
import { eventsRouter } from "../routes/events.routes.js";
import { planRouter } from "../routes/plan.routes.js";
import { sessionRouter } from "../routes/session.routes.js";
import { reviewRouter } from "../routes/review.routes.js";
import { reportRouter } from "../routes/report.routes.js";
import { escalationRouter } from "../routes/escalation.routes.js";
import { conflictRouter } from "../routes/conflict.routes.js";
import { workspaceRouter } from "../routes/workspace.routes.js";
import { skillRouter } from "../routes/skill.routes.js";
import { executionRouter } from "../routes/execution.routes.js";

export function registerRoutes(app: Express): void {
  app.use("/api/v1/auth", authRouter);
  app.use("/api/v1/world", worldRouter);
  app.use("/api/v1/companies", companyRouter);
  app.use("/api/v1/agents", agentRouter);
  app.use("/api/v1/tasks", taskRouter);
  app.use("/api/v1/conversations", conversationRouter);
  app.use("/api/v1/memories", memoryRouter);
  app.use("/api/v1/economy", economyRouter);
  app.use("/api/v1/approvals", approvalRouter);
  app.use("/api/v1/tools", toolRouter);
  app.use("/api/v1/logs", eventRouter);
  app.use("/api/v1/simulation", simulationRouter);
  app.use("/api/v1/events", eventsRouter);
  app.use("/api/v1/plans", planRouter);
  app.use("/api/v1/sessions", sessionRouter);
  app.use("/api/v1/reviews", reviewRouter);
  app.use("/api/v1/reports", reportRouter);
  app.use("/api/v1/escalations", escalationRouter);
  app.use("/api/v1/conflicts", conflictRouter);
  app.use("/api/v1/workspaces", workspaceRouter);
  app.use("/api/v1/skills", skillRouter);
  app.use("/api/v1/executions", executionRouter);
}
